# Generated by Django 3.2.5 on 2021-08-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserD',
        ),
    ]
