# Generated by Django 3.2.5 on 2021-08-11 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GC', '0002_rename_user_userd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userd',
            name='role',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='userd',
            name='status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
